variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dorg.slf4j.simpleLogger.showDateTime=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --fail-at-end
    --show-version

verify:
  stage: test
  tags:
    - oop
  script:
    - 'DISPLAY=:1 mvn $MAVEN_CLI_OPTS test'
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml


oop-exam:
  stage: test
  tags:
    - oop
  script:
    - 'mkdir -p target/exam'
    - 'git diff phase1 HEAD --word-diff src > target/exam/diff.txt'
    - 'sha256sum test/it/polito/extgol/test/* > target/exam/checks.txt'
    - 'sha256sum pom.xml .gitlab-ci.yml >> target/exam/checks.txt'
  artifacts:
    name: "exam"
    paths:
      - target/exam/*
